const { Octokit } = require('@octokit/rest');
const https = require('https');
const config = require('../config');

/**
 * Exchange GitHub OAuth code for access token.
 */
function exchangeCodeForToken(code) {
  return new Promise((resolve, reject) => {
    const body = JSON.stringify({
      client_id: config.github.clientId,
      client_secret: config.github.clientSecret,
      code,
    });

    const options = {
      hostname: 'github.com',
      path: '/login/oauth/access_token',
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Accept': 'application/json',
        'Content-Length': Buffer.byteLength(body),
      },
    };

    const req = https.request(options, (res) => {
      let data = '';
      res.on('data', chunk => { data += chunk; });
      res.on('end', () => {
        try {
          const parsed = JSON.parse(data);
          if (parsed.error) return reject(new Error(parsed.error_description || parsed.error));
          resolve(parsed.access_token);
        } catch (e) {
          reject(e);
        }
      });
    });

    req.on('error', reject);
    req.write(body);
    req.end();
  });
}

/**
 * Get authenticated GitHub user info.
 */
async function getAuthenticatedUser(token) {
  const octokit = new Octokit({ auth: token });
  const { data } = await octokit.users.getAuthenticated();
  return data;
}

/**
 * Push all files from fileMap to a GitHub repository in a single commit.
 * Uses Git Data API for atomic multi-file push.
 */
async function pushFilesToRepo(token, repoName, createNew, fileMap) {
  const octokit = new Octokit({ auth: token });
  const user = await getAuthenticatedUser(token);
  const owner = user.login;

  if (createNew) {
    await octokit.repos.createForAuthenticatedUser({
      name: repoName,
      description: 'WhatsApp bot generated by Sigma MDX — by Muzan Sigma',
      private: false,
      auto_init: true,
    });
    // Wait a moment for GitHub to initialize the repo
    await new Promise(r => setTimeout(r, 1500));
  }

  // Get the HEAD commit SHA
  const { data: refData } = await octokit.git.getRef({
    owner,
    repo: repoName,
    ref: 'heads/main',
  });
  const baseSha = refData.object.sha;

  // Create blobs for each file
  // fileMap values are { content: string, encoding: 'utf8'|'base64' }
  const blobs = await Promise.all(
    Object.entries(fileMap).map(async ([filePath, file]) => {
      const base64Content = file.encoding === 'base64'
        ? file.content
        : Buffer.from(file.content, 'utf8').toString('base64');
      const { data } = await octokit.git.createBlob({
        owner,
        repo: repoName,
        content: base64Content,
        encoding: 'base64',
      });
      return { path: filePath, sha: data.sha, mode: '100644', type: 'blob' };
    })
  );

  // Create tree
  const { data: treeData } = await octokit.git.createTree({
    owner,
    repo: repoName,
    base_tree: baseSha,
    tree: blobs,
  });

  // Create commit
  const { data: commitData } = await octokit.git.createCommit({
    owner,
    repo: repoName,
    message: 'feat: initial WhatsApp bot generated by Sigma MDX\n\nCreated with Sigma MDX Bot Builder by Muzan Sigma',
    tree: treeData.sha,
    parents: [baseSha],
  });

  // Update branch ref
  await octokit.git.updateRef({
    owner,
    repo: repoName,
    ref: 'heads/main',
    sha: commitData.sha,
  });

  return `https://github.com/${owner}/${repoName}`;
}

module.exports = { exchangeCodeForToken, getAuthenticatedUser, pushFilesToRepo };
